import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import logo from '../assets/logo.png';

const ProcessedData = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState({ username: 'User' });
  
  // INITIAL STATE IS NOW EMPTY ARRAY []
  const [processedFiles, setProcessedFiles] = useState([]);

  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
    
    // FETCH REAL DATA (Uncomment this block when your backend endpoint is ready)
    
    const fetchProcessedFiles = async () => {
        try {
            const token = localStorage.getItem('token');
            const res = await axios.get('http://127.0.0.1:5000/processed-files', {
                headers: { Authorization: `Bearer ${token}` }
            });
            setProcessedFiles(res.data);
        } catch (err) {
            console.error("Error fetching processed files:", err);
        }
    };
    fetchProcessedFiles();
    
  }, []);

  const handleLogout = () => {
    localStorage.clear();
    navigate('/login');
  };

  const handleDownload = (fileName) => {
    // Backend download URL example:
    // window.open(`http://127.0.0.1:5000/download/processed/${fileName}`, '_blank');
    alert(`Downloading ${fileName}...`);
  };

  const handleDelete = (id) => {
    if(window.confirm("Are you sure you want to delete this output file?")) {
        // Optimistic UI update
        setProcessedFiles(processedFiles.filter(f => f.id !== id));
        
        // TODO: Call backend to delete
        // axios.delete(`http://127.0.0.1:5000/processed-files/${id}`, ...);
    }
  };

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#0f1115', display: 'flex' }}>
      
      {/* 1. SIDEBAR */}
      <aside style={{ 
        width: '260px', 
        backgroundColor: '#18181b', 
        borderRight: '1px solid #27272a', 
        display: 'flex', 
        flexDirection: 'column',
        padding: '20px',
        flexShrink: 0 
      }}>
        <div style={{ fontSize: '20px', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '10px', color: 'white', marginBottom: '40px', paddingLeft: '10px' }}>
          <img src={logo} alt="Logo" style={{ width: '28px', height: '28px', borderRadius: '4px' }} />
          StreamForge
        </div>

        <nav style={{ display: 'flex', flexDirection: 'column', gap: '10px', flexGrow: 1 }}>
          <SidebarItem label="Overview" icon="🏠" onClick={() => navigate('/dashboard')} />
          <SidebarItem label="All Pipelines" icon="🚀" onClick={() => navigate('/pipelines')} />
          <SidebarItem label="Data Sources" icon="🗄️" onClick={() => navigate('/datasources')} />
          <SidebarItem label="Processed Data" icon="📦" active /> 
          <SidebarItem label="Settings" icon="⚙️" />
        </nav>

        {/* Profile Section */}
        <div style={{ borderTop: '1px solid #27272a', paddingTop: '20px', marginTop: '10px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '10px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', overflow: 'hidden' }}>
                <div style={{ width: '32px', height: '32px', background: '#3f3f46', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '14px', flexShrink: 0 }}>
                    👤
                </div>
                <div style={{ overflow: 'hidden' }}>
                    <p style={{ margin: 0, fontSize: '14px', fontWeight: '500', color: 'white', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: '85px' }}>{user.username}</p>
                    <p style={{ margin: 0, fontSize: '12px', color: '#9ca3af' }}>Free Plan</p>
                </div>
            </div>
            <button onClick={handleLogout} style={{ background: '#27272a', border: '1px solid #3f3f46', color: '#ef4444', padding: '8px 12px', borderRadius: '6px', fontSize: '13px', fontWeight: '500', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0, transition: 'background 0.2s' }}>
                <span>🚪</span> Logout
            </button>
        </div>
      </aside>

      {/* 2. MAIN CONTENT */}
      <main style={{ flexGrow: 1, display: 'flex', flexDirection: 'column', overflowX: 'hidden' }}>
        <div style={{ padding: '40px', width: '100%', boxSizing: 'border-box' }}>
          
          {/* Header */}
          <div style={{ marginBottom: '40px' }}>
            <h1 style={{ fontSize: '32px', marginBottom: '10px', color: 'white' }}>Processed Data</h1>
            <p className="muted" style={{ margin: 0, color: '#9ca3af' }}>Download the output files generated by your pipelines.</p>
          </div>

          {/* Files List */}
          <div className="card" style={{ padding: '0', overflow: 'hidden', background: '#18181b', border: '1px solid #27272a', borderRadius: '12px' }}>
            <div style={{ padding: '20px', borderBottom: '1px solid #27272a' }}>
              <h3 style={{ margin: 0, fontSize: '18px', color: 'white' }}>Output Files</h3>
            </div>
            
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #27272a', color: '#9ca3af', fontSize: '14px', backgroundColor: '#1f1f23' }}>
                  <th style={{ padding: '15px 20px', fontWeight: '500' }}>File Name</th>
                  <th style={{ padding: '15px 20px', fontWeight: '500' }}>Source Pipeline</th>
                  <th style={{ padding: '15px 20px', fontWeight: '500' }}>Type</th>
                  <th style={{ padding: '15px 20px', fontWeight: '500' }}>Size</th>
                  <th style={{ padding: '15px 20px', fontWeight: '500' }}>Date Created</th>
                  <th style={{ padding: '15px 20px', fontWeight: '500', textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {processedFiles.length === 0 ? (
                    <tr>
                        <td colSpan="6" style={{ padding: '40px', textAlign: 'center', color: '#666' }}>
                            No processed files found. Run a pipeline to generate data.
                        </td>
                    </tr>
                ) : (
                    processedFiles.map(file => (
                    <tr key={file.id} style={{ borderBottom: '1px solid #27272a', color: 'white', fontSize: '14px' }}>
                        <td style={{ padding: '15px 20px', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '10px' }}>
                            <span style={{ fontSize: '16px' }}>
                                {file.type === 'Excel' ? '📊' : file.type === 'JSON' ? '{}' : '📄'}
                            </span> 
                            {file.name}
                        </td>
                        <td style={{ padding: '15px 20px', color: '#9ca3af' }}>{file.pipeline}</td>
                        <td style={{ padding: '15px 20px', color: '#9ca3af' }}>
                            <span style={{ 
                                background: file.type === 'Excel' ? 'rgba(22, 163, 74, 0.2)' : file.type === 'JSON' ? 'rgba(251, 191, 36, 0.2)' : 'rgba(59, 130, 246, 0.2)',
                                color: file.type === 'Excel' ? '#16a34a' : file.type === 'JSON' ? '#fbbf24' : '#3b82f6',
                                padding: '2px 8px', borderRadius: '4px', fontSize: '12px' 
                            }}>
                                {file.type}
                            </span>
                        </td>
                        <td style={{ padding: '15px 20px', color: '#9ca3af' }}>{file.size}</td>
                        <td style={{ padding: '15px 20px', color: '#9ca3af' }}>{file.date}</td>
                        <td style={{ padding: '15px 20px', textAlign: 'right' }}>
                            <button 
                                onClick={() => handleDownload(file.name)}
                                className="btn btn-ghost" 
                                style={{ padding: '6px 12px', fontSize: '12px', color: '#3b82f6', border: '1px solid #3b82f6', marginRight: '10px' }}
                            >
                                ⬇ Download
                            </button>
                            <button 
                                onClick={() => handleDelete(file.id)}
                                className="btn btn-ghost" 
                                style={{ padding: '6px 12px', fontSize: '12px', color: '#ef4444', border: '1px solid #ef4444' }}
                            >
                                ✕
                            </button>
                        </td>
                    </tr>
                    ))
                )}
              </tbody>
            </table>
          </div>

        </div>
      </main>
    </div>
  );
};

// Helper for Sidebar Items
const SidebarItem = ({ label, icon, active, onClick }) => (
  <div 
    onClick={onClick}
    style={{ 
      display: 'flex', 
      alignItems: 'center', 
      gap: '12px', 
      padding: '10px 15px', 
      borderRadius: '6px', 
      cursor: 'pointer',
      backgroundColor: active ? '#27272a' : 'transparent',
      color: active ? 'white' : '#9ca3af',
      transition: 'background 0.2s'
    }}
    onMouseOver={(e) => !active && (e.currentTarget.style.backgroundColor = 'rgba(255,255,255,0.05)')}
    onMouseOut={(e) => !active && (e.currentTarget.style.backgroundColor = 'transparent')}
  >
    <span>{icon}</span>
    <span style={{ fontSize: '14px', fontWeight: '500' }}>{label}</span>
  </div>
);

export default ProcessedData;