import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import logo from '../assets/logo.png';
import '../App.css'; // Import shared styles

const ProcessedData = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState({ username: 'User' });
  const [processedFiles, setProcessedFiles] = useState([]); // Stores fetched files from DB

  useEffect(() => {
    // 1. Load User
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
    
    // 2. FETCH PROCESSED FILES FROM DB
    const fetchProcessedFiles = async () => {
        try {
            const token = localStorage.getItem('token');
            const res = await axios.get('http://127.0.0.1:5000/processed-files', {
                headers: { Authorization: `Bearer ${token}` }
            });
            setProcessedFiles(res.data);
        } catch (err) {
            console.error("Error fetching processed files:", err);
        }
    };
    fetchProcessedFiles();
    
  }, []);

  const handleLogout = () => {
    localStorage.clear();
    navigate('/login');
  };

  const handleDownload = (fileName) => {
    // Open in new tab to trigger download from backend
    window.open(`http://127.0.0.1:5000/download/processed/${fileName}`, '_blank');
  };

  const handleDelete = async (id, fileName) => {
    if(window.confirm(`Are you sure you want to delete ${fileName}?`)) {
        try {
            const token = localStorage.getItem('token');
            // USE ID IN URL to delete from DB and Disk
            await axios.delete(`http://127.0.0.1:5000/processed-files/${id}`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            // Update UI
            setProcessedFiles(processedFiles.filter(f => f.id !== id));
        } catch (err) {
            alert("Failed to delete file");
        }
    }
  };

  return (
    <div className="app-container">
      
      {/* 1. SIDEBAR */}
      <aside className="sidebar">
        <div className="sidebar-logo">
          <img src={logo} alt="Logo" style={{ width: '28px', height: '28px', borderRadius: '4px' }} />
          StreamForge
        </div>

        <nav className="sidebar-nav">
          <SidebarItem label="Overview" icon="🏠" onClick={() => navigate('/dashboard')} />
          <SidebarItem label="All Pipelines" icon="🚀" onClick={() => navigate('/pipelines')} />
          <SidebarItem label="Data Sources" icon="🗄️" onClick={() => navigate('/datasources')} />
          <SidebarItem label="Processed Data" icon="📦" active /> 
          <SidebarItem label="Settings" icon="⚙️" onClick={() => navigate('/settings')}/>
        </nav>

        {/* Profile Section */}
        <div className="sidebar-profile">
            <div className="flex items-center gap-10" style={{ overflow: 'hidden' }}>
                <div className="profile-avatar">
                    👤
                </div>
                <div style={{ overflow: 'hidden' }}>
                    <p style={{ margin: 0, fontSize: '14px', fontWeight: '500', color: 'white', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: '85px' }}>{user.username}</p>
                    <p className="text-muted" style={{ margin: 0, fontSize: '12px' }}>Free Plan</p>
                </div>
            </div>
            <button 
                onClick={handleLogout}
                className="btn-sidebar-logout"
            >
                <span>🚪</span> Logout
            </button>
        </div>
      </aside>

      {/* 2. MAIN CONTENT */}
      <main className="main-content">
        <div className="content-wrapper">
          
          {/* Header */}
          <div style={{ marginBottom: '40px' }}>
            <h1 style={{ fontSize: '32px', marginBottom: '10px', margin: 0 }}>Processed Data</h1>
            <p className="text-muted" style={{ margin: 0 }}>Download the output files generated by your pipelines.</p>
          </div>

          {/* Files List */}
          <div className="card">
            <div style={{ padding: '20px', borderBottom: '1px solid var(--border-light)' }}>
              <h3 style={{ margin: 0, fontSize: '18px' }}>Output Files</h3>
            </div>
            
            <table className="data-table">
              <thead>
                <tr className="table-header">
                  <th>File Name</th>
                  <th>Type</th>
                  <th>Size</th>
                  <th>Created</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {processedFiles.length === 0 ? (
                    <tr>
                        <td colSpan="5" className="text-center text-muted" style={{ padding: '40px' }}>
                            No processed files found. Run a pipeline to generate data.
                        </td>
                    </tr>
                ) : (
                    processedFiles.map((file) => (
                    <tr key={file.id} className="table-row">
                        <td style={{ fontWeight: '600', display: 'flex', alignItems: 'center', gap: '10px' }}>
                            <span style={{ fontSize: '16px' }}>
                                {file.type === 'Excel' ? '📊' : 
                                 file.type === 'JSON' ? '{}' : 
                                 file.type === 'Database' ? '🗄️' : 
                                 file.type === 'Image' ? '🖼️' : '📄'}
                            </span> 
                            {file.name}
                        </td>
                        <td className="text-muted">
                            <span style={{ 
                                background: file.type === 'Excel' ? 'rgba(22, 163, 74, 0.2)' : 
                                            file.type === 'JSON' ? 'rgba(251, 191, 36, 0.2)' : 
                                            file.type === 'Database' ? 'rgba(139, 92, 246, 0.2)' : 
                                            file.type === 'Image' ? 'rgba(236, 72, 153, 0.2)' :
                                            'rgba(59, 130, 246, 0.2)',
                                color: file.type === 'Excel' ? '#16a34a' : 
                                       file.type === 'JSON' ? '#fbbf24' : 
                                       file.type === 'Database' ? '#8b5cf6' : 
                                       file.type === 'Image' ? '#ec4899' :
                                       '#3b82f6',
                                padding: '2px 8px', borderRadius: '4px', fontSize: '12px' 
                            }}>
                                {file.type}
                            </span>
                        </td>
                        <td className="text-muted">{file.size}</td>
                        <td className="text-muted">{file.date}</td>
                        <td style={{ textAlign: 'right' }}>
                            <button 
                                onClick={() => handleDownload(file.name)}
                                className="btn btn-ghost" 
                                style={{ padding: '6px 12px', fontSize: '12px', color: 'var(--primary)', borderColor: 'var(--primary)', marginRight: '10px' }}
                            >
                                ⬇ Download
                            </button>
                            <button 
                                onClick={() => handleDelete(file.id, file.name)}
                                className="btn btn-ghost" 
                                style={{ padding: '6px 12px', fontSize: '12px', color: 'var(--danger)', borderColor: 'var(--danger)' }}
                            >
                                ✕
                            </button>
                        </td>
                    </tr>
                    ))
                )}
              </tbody>
            </table>
          </div>

        </div>
      </main>
    </div>
  );
};

// Helper for Sidebar Items
const SidebarItem = ({ label, icon, active, onClick }) => (
  <div className={`sidebar-item ${active ? 'active' : ''}`} onClick={onClick}>
    <span>{icon}</span>
    <span>{label}</span>
  </div>
);

export default ProcessedData;